version: '3'

services:
  drift_monitor:
    build:
      context: .
      dockerfile: docker/drift_monitor.Dockerfile
    image: christianhilscher/drift_monitor:latest
    volumes:
      - /app/data:/data
    environment:
      - API_SERVER_URL=http://api-server:5000
    networks:
      - common_network
